### PR TITLE
Create pull_request_template.md

### LINKED ISSUE #72: Create Pull Request Template
Regarding the Senior Design Portfolio 2, to have outstanding pull requests, your repository should have contribution guidelines. 

This issue should create a pull request template in the repository's default branch. This should be in Markdown Language following the format of [https://github.com/Graylog2/graylog2-server/pull/14284](url). 

Screenshot 2024-03-26 at 3 41 33 PM

### PR DESCRIPTION
**Pull request by dafneMena**
This PR closes #72. 

I've created a template for a meaningful PR so that we can use this for future pull requests. This is mandatory in the Senior Design Portfolio II. No project code files were changed.

Please take a look at the template and let me know If you feel I should modify any sections. 

Screenshot 2024-03-26 at 4 00 09 PM

### CODE REVIEW

**Review by RedPenguin88 — APPROVED** [review]
This looks good to me and follows a similar structure to the pull requests we have already had. Additionally, it satisfies the requirements for the Design Document II.

**Review by B-Timok — APPROVED** [review]
Nice. I'll be sure to follow this template for any future Pull Requests

**Review by trevortippery — APPROVED** [review]
This looks great, will be following the template from now. Great to use in the DP2 as well.

**Review by Linkaloo — APPROVED** [review]
This looks good, I don't know if automatically generates a template on PR. It would be cool if it did and there might be some functionality here that allows that: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

Vercel is failing cause of main problems, nothing to do with this

**Pull request merged**
