### PR TITLE
Login testing

### LINKED ISSUE #28: Login unit testing
Add a file for unit testing the login page.
This should test:
- the text fields
- the login function is called
- anything else needed

### PR DESCRIPTION
**Pull request by Aligary**
## Description
This PR introduces tests by starting with the Login Page. It tests that the components are being rendered when/where they should be. 

## Related Issue
Closes #28. 

## Type of Changes
Please select the relevant option:
- [x] Added tests for the Login page
- [x] Added dependency @testing-library/jest-dom
- [x] Added dependency @types/redux-mock-store
- [x] Added test id's to components in the Login Page
- [x] Added coverage provider to vite.config.ts

## Things to Update
Please add any features, buttons, or pages that might need updating in the future:
- [ ] Testing for any additional lines in this file.

### CODE REVIEW

**Review by Linkaloo — APPROVED** [review]
I am going to search to see if we can avoid putting testids everywhere cause thats annoying. Looks good though

**Review by dafneMena — APPROVED** [review]
Nice Job! keep up the good work

**Review by trevortippery — APPROVED** [review]
No problems found. Approved!

**Review by morenj — APPROVED** [review]
Great work on the tests. Everything looks good on my end. Approved. Thank you for your hard work.

**Review by tbmcallister — APPROVED** [review]
This looks great, and it’ll really help us in the future with our CI/CD

Great work!

**Comment by Aligary** [comment]
This PR will not be merged. There were a noticeable amount of merge conflicts in the package-lock.json. I went in to try to resolve every conflict but after looking throught 16000+ lines of code, i couldnt resolve them. I went ahead and just created a new branch from the up-to-date main and redid the testing there.

**Pull request closed without merging**
