### PR TITLE
Add Marker Icons

### LINKED ISSUE #37: Add Marker Icons
We are going to need a file containing all the marker icons we want to use.
These are, hopefully, svgs.

Icons are the following:
image

There may be more but these are what are shown on the figma.
Essentially make a folder, probably in assets, saying markers and add all the marker svgs. Then make an index file exporting them. 

Something like:
```
import Cone from 'cone.svg';
export {
Cone
}
```

### PR DESCRIPTION
**Pull request by tbmcallister**
This PR closes #37 

This PR adds in several images, all in .svg format. These markers will be useful when the user wishes to add in different types of road obstructions, or just so that we can communicate with the user about different road obstructions. I added in the required images from the task description:

Cone:
image

CarAccident:
image

Pothole:
image

RoadDamage:
image

I also added in another image that I believe will be useful.
WarningSign:

image

These are all exported in the assets/markers directory. 

Please let me know if you have any suggestions for improvement, and thank you!

### CODE REVIEW

**Review by Aligary — APPROVED** [review]
Thanks!

**Review by morenj — APPROVED** [review]
Amazing, thank you. 

Does anyone know the difference between adding the SVGs in src/assets vs public/images?

Just curious since since I've seen both options before.

**Comment by Linkaloo** [comment]
> Does anyone know the difference between adding the SVGs in src/assets vs public/images?

The main difference is how they are processed in the build step.
Essentially public/ images are not processed in the web pack just copied in the build step, this means you cant use JS on them.
src/assets/ images are processed by the web pack meaning you can use JS on them, but they might make the build bigger.

https://medium.com/@oezhan/react-src-folder-or-public-folder-for-images-5a99ca5ec72f

I've generally seen more usage or src/assets but I can do some more research into this.

**Comment by morenj** [comment]
That's explains a lot. Thank you I appreciate your fast response.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Review by Linkaloo — APPROVED** [review]
Nice, these look good

**Pull request merged**
