### PR TITLE
Configured the Web App to be PWA Installable

### LINKED ISSUE #11: Configuring Application to Work as a PWA
As a user, I would like to be able to download this site onto my mobile devices and computer as an application. In order to do this, the site needs to be configured as a Progressive Web App (PWA).

PWAs enable users to use our site as if it were an app, complete with push notifications, location tracking, etc. To configure our site as a PWA, we need to implement the following files:
- `manifest.json`
- `serviceWorker.ts`

Additionally, we will need to make several changes to `index.html` in order to allow the user to download the site as an app. Please investigate these and implement them as needed.

For help, please reference this article: https://www.freecodecamp.org/news/build-a-pwa-from-scratch-with-html-css-and-javascript/

### PR DESCRIPTION
**Pull request by KingJordan152**
This PR closes #11.

# Description

For this PR, I configured the application to be PWA installable on all major devices. 

PWAs, or **Progressive Web Apps**, are web apps that have been configured in such a way that enables them to be downloaded onto the user's device as if they were a native application. This applies to both desktop and mobile devices! PWAs also broaden the capabilities of a normal website by being able to access special APIs, send mobile push notifications like a native app, and even work offline!

Currently, offline functionality is disabled until we have set up hosting using _HTTPS_. However, in the mean time, login capabilities are cached and mobile push notifications are WiP!

You can tell whether our site meets the minimum requirements to be PWA installable by opening Chrome's Dev Tools, then going to the Lighthouse tab and running a performance check, ensuring the "Progressive Web App" category is checked. After running the test, Lighthouse report the following message: 

> "Web app manifest and service worker meet the installability requirements"

Additionally, the PWA section report all green statuses as such:

image

# Changes Made

This following a detailed breakdown of all the changes made and why I made them:

> [!note]
> Almost everything under `client/dev-dist` was automatically generated by `vite-plugin-pwa` in order to make the web app PWA installable. If you can still see it under "Files changed" please ignore it when reviewing.

- Installed `vite-plugin-pwa` to set up the foundation for making our site PWA installable.
- Created a `manifest` field in `vite.config.ts` to supply browsers with sufficient metadata to allow our application to be PWA installable
- Added additional metadata to the public `index.html` file to allow allow site crawlers and search engines to more easily scrape our site
  - This also helps with configuring the application to be a PWA
- Created numerous icons that can be used across a variety of devices
  - Created a favicon by taking our updated logo and adjusting the SVG code to eliminate margins and increase the overall size. Now, when loading up the site, there should be an icon next to the title on the tab bar!
    - image
  - Created an `apple-touch-icon` that is used by iOS devices when creating an app bookmark on the user's home screen. This enables our web app to feel like a native application.
    - image
  - Created several images of varying sizes to be used as desktop icons by most major browsers (i.e., Edge, Chrome, Safari, etc.)
    - image
- Made our default theme color the same orange (#FB7110) as the cone in our logo. This causes the title bar to be orange when the installed PWA is being used:
  - Desktop: 
    - Screenshot 2024-03-24 at 3 34 40 PM
  - Mobile (iOS): 
    - Screenshot 2024-03-24 at 3 36 10 PM

> [!note]
> If you aren't a fan of the icon used, please let me know so I can change it. It will take some time to rework the original SVG, but it can be done.

# Installing the PWA

The PWA version of our site can be installed on almost any major browser on desktop and Android devices. For iOS, PWAs can only be installed via Safari.

## Mobile (iOS)

1. Tap the "sharrow" icon (pictured here in the middle). 
image  

2. Tap the "Add to Home Screen" option. 
image

3. Tap "Add" in the upper right corner. 
image

4.  The site should now be accessible from the home screen of your iPhone!

## Chrome

1. On the far right side of the search bar, click the middle icon that says "Install Roadwatch" 
image

2. Click "Install" 
image

3. You should now be able to drag the icon onto your desktop or access it from the Chrome applications folder!

### CODE REVIEW

**Review by Linkaloo — APPROVED** [review]
Everything looks good, I'll be curious how this will work now that we have the app hosted as well.
The only thing you could add is a description of what the serve command in scripts is doing. I think I get the jist, but if you have more details about it that would be nice.

**Comment by KingJordan152** [comment]
> Everything looks good, I'll be curious how this will work now that we have the app hosted as well. The only thing you could add is a description of what the serve command in scripts is doing. I think I get the jist, but if you have more details about it that would be nice.

You just reminded me that I need to remove that. That was used for internal testing and isn't necessary anymore since we're hosting the site now. Deleting now.

**Review by RedPenguin88 — APPROVED** [review]
I was able to install as a PWA. I verified that the app manifest reflects the changes you made in this PR through Firefox's web developer tools. Additionally, when installed, I see that the icons work and that the title bar reflects the orange in our logo.

Personally, I like the icon as is and think no changes are necessary. Overall, great job!

**Review by tbmcallister — APPROVED** [review]
Icons look great and I like the layout of the PWA. This will greatly help us going forward in developing this project.

Thank you for the instructions on how to get it set up!

Everything looks great, good job!

**Pull request merged**
