### PR TITLE
MonoRepo Resturcture

### LINKED ISSUE #15: Restructure for Server and Client
This is a massive folder and project restructuring.
There are 2 main folders, client and server. Each has their own package file, eslint rules, and tsconfig that they will follow.
Client represents the react part of our app. The front end that users see.
Server represents any backend tasks we have to do. This is usually storing and retrieving stuff from a database.

### PR DESCRIPTION
**Pull request by Linkaloo**
This PR restructures the project to include 2 top level folders named "client" and "server".
The Client represents anything front facing, that is the entire react application and the components required.
The Server represents any logic we do not want to expose. In general this is used for inserting and retrieving elements into a database, however it can also handle anything else we need it to.

The root of our project contains a package and package-lock files. These are important as I have used npm workspaces to distinguish the fact that there exists 2 projects under here. 
If you are developing from root you can access commands under client or server by using the -w <client/server> flag. It stands for workspace <what the workspace is>. To do something for every workspace you can do -ws.

Everything we had and that was pushed into the project before is now inside the client folder.
The client folder holds its own lint, package, and tsconfig files and are independent from the server.
You can easily start the client by doing "npm run dev-client" from the root folder or you can cd into client and run the npm commands in there.

The server folder is much the same. You can do "npm run dev-server" to start it. The server is a node.js server using express to expose routes. 
The server uses a docker-compose.yml file to create a mongoDB docker image that it then uses for development purposes. 
The file structure of server consits of the following:
- config: for any configuration files
- controllers: for the main logic that we will do for each route
- models: that depict what the database is going to hold
- routes: the routes we want to expose so that we can use them

Please make a copy of the .env.example file and rename it to .env
closes #15

### CODE REVIEW

**Review by valdea13 — APPROVED** [review]
Since I basically made no changes yet, my portion is safe!

**Review by trevortippery — APPROVED** [review]
My changes are still there and safe.

**Review by dafneMena — APPROVED** [review]
All good on my end!

**Review by Aligary — APPROVED** [review]
My files look safe!

**Review by morenj — APPROVED** [review]
It's good to go from my end also.

**Review by RedPenguin88 — APPROVED** [review]
I haven't pushed any relevant changes. Everything looks good!

**Review by B-Timok — APPROVED** [review]
No changes, so all good here.

**Pull request merged**
