### PR TITLE
38 Community Data Model

### PR DESCRIPTION
**Pull request by sooble13**
## Description
This PR introduces a new Community schema, which allows the storage and retrieval of community information. In addition, this will be used on the community page to get the list of available communities.

## Related Issue
Closes https://github.com/UNLV-CS472-672/2024-S-GROUP1-Roadwatch/issues/38

## Type of Changes
- [ ] Bug fix
- [x] New feature
- [ ] Enhancement
- [x] Documentation update
- [ ] Other (please specify)
      

## Things to Update
- [ ] Button Functionality
- [ ] Code Documentation
- [ ] Mobile Responsiveness
- [ ] Code testing
- [x] Other (Addition of more Community Fields).

### CODE REVIEW

**Review by Aligary — APPROVED** [review]
I see that you added the instructions page in this PR in addition to #65. The instructions PR is already in main, i don't know if this would break anything. 

Other than that, great job!

**Comment by sooble13** [comment]
> I see that you added the instructions page in this PR in addition to #65. The instructions PR is already in main, i don't know if this would break anything.
> 
> Other than that, great job!

I don't believe it should? I merged main into this branch, so hopefully it'll recognize that instead.

**Comment by Linkaloo** [comment]
Your branch is currently 2 commits behind main and 2 commits ahead. 1 of those behind commits is the instructions page and the 1 of the ahead commits is the instructions page. I think that might be why. So just git pull main and merge it into this branch. I think it would probably auto resolve but not bad to just merge it when its weird like this
image

**Review by Linkaloo — APPROVED** [review]
Everything looks good

**Comment by sooble13** [comment]
> Your branch is currently 2 commits behind main and 2 commits ahead. 1 of those behind commits is the instructions page and the 1 of the ahead commits is the instructions page. I think that might be why. So just git pull main and merge it into this branch. I think it would probably auto resolve but not bad to just merge it when its weird like this image

I just fixed this. I don't know what the problem was, but it should be caught up to main now!

**Review by trevortippery — APPROVED** [review]
Looks good I have no complaints. Approved 🎉

**Pull request merged**
