### PR TITLE
Created a customized button component using the MUI Button

### LINKED ISSUE #4: Button Component
Create a reusable button component

image

### PR DESCRIPTION
**Pull request by Aligary**
closes #4 
Created a custom button component in order to keep the styling the same throughout the app. 

Example import: 
Screenshot 2024-03-19 at 4 49 13 PM

The color is the orange of the traffic cone from the logo 
Screenshot 2024-03-19 at 4 14 30 PM

This utilizes the MUI Button component. 
Developer should create a div to customize the sizing of the button. 

It has a required onClick prop that the developer should pass in in order to complete an action. For example, it would be a function that reroutes the app to the desired page. 

The label of the button is the contents that is typed in between the tags. 
Screenshot 2024-03-19 at 4 40 12 PM

### CODE REVIEW

**Review by tbmcallister — APPROVED** [review]
I like the traffic cone color- the code is documented well and has room for customization. I like the onClick prop. Looks good, good job!

**Comment by trevortippery** [comment]
Looks good, I like that you matched it with the theme/color of our new project logo and gave instructions on how to use it.

**Review by trevortippery — APPROVED** [review]

**Review by RedPenguin88 — APPROVED** [review]
Theming is great and looks good overall. Since this custom button uses mui, should we amend our TextField and PasswordFields to also use mui for consistency purposes?

**Review by Linkaloo — APPROVED** [review]
Looks good, I think the function type "React.FC<CustomButtonProps>" doesn't need to be there but not a blocker

**Pull request merged**
