### PR TITLE
Style Audit: Ensure Consistent Font Families

### LINKED ISSUE #126: Style Audit: Ensure Consistent Font Families
# Description

Throughout the site, there are instances where the fonts aren't the same. For example:

image

All of the arrows on the Home page alone point to text that have different fonts.

Please comb through the CSS of the site and ensure all the text uses the same font.

# Acceptance Criteria

- Make all the components use the same `font-family` attribute
- Change the `font-family` to either Roboto or Open Sans (https://fonts.google.com/specimen/Open+Sans)
  - Open Sans is a good industry-standard font, but you have to import it to the project. `Roboto` is preinstalled on any system, so it's guaranteed to work

# Help

It would be easier to do this on a global level, that way you don't have to go into each component's Sass file and overwrite the `font-family`. Additionally, this will ensure that any future components will use the new `font-family`. You will can do this in `client/src/index.css`, but make sure the file is first imported into `client/src/main.tsx`. If you only add new styles to the `:root`, you shouldn't have to add a class name to any of the components.

Also, in `index.css`, after you import it into `main.tsx`, make sure to remove these two lines:
```css
color-scheme: light dark;
color: rgba(255, 255, 255, 0.87);
```
These cause certain parts of the screen to go black when they shouldn't have to.

If you want to use Open Sans, view this link to learn how to import it to the project: https://stackoverflow.com/a/42144167

### PR DESCRIPTION
**Pull request by B-Timok**
## Description
This pull request standardizes the font across the entire website. All text now uses the Open Sans font, which was imported from Google Fonts. This change was made globally in the `index.css` file, ensuring that all current and future components will use this font.

## Related Issue
Closes #126 

## Type of Changes
- [x] Enhancement

## Changes
- Imported Open Sans font from Google Fonts in `index.css`.
- Set Open Sans as the default font in `index.css`.
- Removed unnecessary `color-scheme` and `color` lines from `index.css`.
- Imported `index.css` into `main.tsx` to apply the global styles.

## Things to Update
- [ ] Code Documentation 

## Screenshots
image
image

## Additional Notes
I've also went through each scss file to make sure there aren't any conflicting local fonts being set just in case.

### CODE REVIEW

**Review by Aligary — APPROVED** [review]
great work!

**Review by tbmcallister — APPROVED** [review]
Consistent fonts will really help us have a good and pretty looking MVP. Nice work!

**Review by sooble13 — APPROVED** [review]
Thanks for creating uniformity in our components! It doesn't seem like you missed an area where a different local font is being used. Great work!

**Comment by trevortippery** [comment]
This pull request needs to be merged first before the pull request #136

**Comment by trevortippery** [comment]
> This pull request needs to be merged first before the pull request #136.

Nevermind since the `Navbar` component does not reference the new `index.css` file

**Pull request merged**
